// Generated by tools/gen_panels.py -- do not edit by hand.
// Control centres in millimetres (see res/*.svg).
#pragma once

namespace layout
{
struct Mm
{
    float x, y;
};
struct MmBox
{
    float x, y, w, h; // centre and size
};

namespace osc
{
constexpr int HP = 18;
constexpr Mm OSC1_PITCH = {10.000f, 17.500f};
constexpr Mm DETUNE = {25.000f, 17.500f};
constexpr Mm OSC2_PITCH = {40.000f, 17.500f};
constexpr Mm SAW1 = {6.900f, 32.500f};
constexpr Mm PULSE1 = {13.100f, 32.500f};
constexpr Mm PW = {25.000f, 32.500f};
constexpr Mm SAW2 = {36.900f, 32.500f};
constexpr Mm PULSE2 = {43.100f, 32.500f};
constexpr Mm ENV_PITCH_BOTH = {6.400f, 44.500f};
constexpr Mm ENV_PITCH_INV = {13.600f, 44.500f};
constexpr Mm ENV_PW_INV = {36.400f, 44.500f};
constexpr Mm ENV_PW_BOTH = {43.600f, 44.500f};
constexpr Mm ENV_PITCH = {10.000f, 58.000f};
constexpr Mm OSC2_PW_OFFSET = {25.000f, 58.000f};
constexpr Mm OSC2_PW_OFFSET_ATT = {25.000f, 46.000f};
constexpr Mm ENV_PW = {40.000f, 58.000f};
constexpr Mm CROSSMOD = {10.000f, 75.000f};
constexpr Mm SYNC = {21.600f, 75.000f};
constexpr Mm OSC2_KEYTRACK = {28.400f, 75.000f};
constexpr Mm BRIGHT = {40.000f, 75.000f};
constexpr Mm OSC1_VOL = {55.750f, 17.500f};
constexpr Mm OSC2_VOL = {55.750f, 35.000f};
constexpr Mm RING_VOL = {55.750f, 52.500f};
constexpr Mm NOISE_VOL = {55.750f, 70.000f};
constexpr Mm NOISE_COLOR = {55.750f, 82.500f};
constexpr Mm TRANSPOSE = {70.200f, 17.500f};
constexpr Mm TUNE = {82.700f, 17.500f};
constexpr Mm UNISON_VOICES = {70.200f, 47.500f};
constexpr Mm UNISON_DETUNE = {82.700f, 47.500f};
constexpr MmBox VOICES_DISPLAY = {76.450f, 60.600f, 8.000f, 5.000f};
constexpr Mm VOCT_INPUT = {9.500f, 101.000f};
constexpr Mm ENV_PITCH_INPUT = {21.500f, 101.000f};
constexpr Mm ENV_PW_INPUT = {33.500f, 101.000f};
constexpr Mm OSC2_PW_OFFSET_INPUT = {45.500f, 101.000f};
constexpr Mm WAVE1_INPUT = {9.500f, 117.500f};
constexpr Mm WAVE2_INPUT = {21.500f, 117.500f};
constexpr Mm OSC1_VOL_INPUT = {33.500f, 117.500f};
constexpr Mm OSC2_VOL_INPUT = {45.500f, 117.500f};
constexpr Mm RING_VOL_INPUT = {57.500f, 117.500f};
constexpr Mm OUT_OUTPUT = {77.000f, 109.000f};
} // namespace osc

namespace filter
{
constexpr int HP = 20;
constexpr Mm FOUR_POLE = {7.600f, 6.100f};
constexpr Mm CUTOFF = {10.000f, 18.500f};
constexpr Mm RESONANCE = {25.000f, 18.500f};
constexpr Mm ENV_AMOUNT = {40.000f, 18.500f};
constexpr Mm KEYTRACK = {10.000f, 37.500f};
constexpr Mm MODE = {25.000f, 37.500f};
constexpr MmBox MODE_DISPLAY = {40.000f, 36.000f, 12.000f, 7.000f};
constexpr Mm PUSH = {10.000f, 55.000f};
constexpr Mm BP_BLEND = {25.000f, 55.000f};
constexpr Mm XPANDER = {40.000f, 52.800f};
constexpr Mm INVERT = {53.600f, 6.100f};
constexpr Mm ATTACK = {55.263f, 18.500f};
constexpr Mm DECAY = {67.787f, 18.500f};
constexpr Mm SUSTAIN = {80.312f, 18.500f};
constexpr Mm RELEASE = {92.837f, 18.500f};
constexpr Mm CURVE = {61.525f, 32.000f};
constexpr Mm VELOCITY = {86.575f, 32.000f};
constexpr Mm CUTOFF_ATT = {53.450f, 57.000f};
constexpr Mm CUTOFF_INPUT = {60.950f, 57.000f};
constexpr Mm RES_ATT = {70.150f, 57.000f};
constexpr Mm RES_INPUT = {77.650f, 57.000f};
constexpr Mm ENV_AMT_ATT = {86.850f, 57.000f};
constexpr Mm ENV_AMT_INPUT = {94.350f, 57.000f};
constexpr Mm MODE_ATT = {53.450f, 76.500f};
constexpr Mm MODE_INPUT = {60.950f, 76.500f};
constexpr Mm ATTACK_ATT = {70.150f, 76.500f};
constexpr Mm ATTACK_INPUT = {77.650f, 76.500f};
constexpr Mm DECAY_ATT = {86.850f, 76.500f};
constexpr Mm DECAY_INPUT = {94.350f, 76.500f};
constexpr Mm IN_INPUT = {10.000f, 112.000f};
constexpr Mm GATE_INPUT = {23.000f, 112.000f};
constexpr Mm VEL_INPUT = {36.000f, 112.000f};
constexpr Mm VOCT_INPUT = {49.000f, 112.000f};
constexpr Mm OUT_OUTPUT = {75.500f, 112.000f};
constexpr Mm ENV_OUTPUT = {89.500f, 112.000f};
} // namespace filter

namespace voices
{
constexpr int HP = 12;
constexpr Mm LEVELS = {30.480f, 17.500f};
constexpr Mm PAN_1 = {9.030f, 36.000f};
constexpr Mm PAN_2 = {23.330f, 36.000f};
constexpr Mm PAN_3 = {37.630f, 36.000f};
constexpr Mm PAN_4 = {51.930f, 36.000f};
constexpr Mm PAN_5 = {9.030f, 51.500f};
constexpr Mm PAN_6 = {23.330f, 51.500f};
constexpr Mm PAN_7 = {37.630f, 51.500f};
constexpr Mm PAN_8 = {51.930f, 51.500f};
constexpr Mm PAN_CV_1 = {9.030f, 78.000f};
constexpr Mm PAN_CV_2 = {23.330f, 78.000f};
constexpr Mm PAN_CV_3 = {37.630f, 78.000f};
constexpr Mm PAN_CV_4 = {51.930f, 78.000f};
constexpr Mm PAN_CV_5 = {9.030f, 93.000f};
constexpr Mm PAN_CV_6 = {23.330f, 93.000f};
constexpr Mm PAN_CV_7 = {37.630f, 93.000f};
constexpr Mm PAN_CV_8 = {51.930f, 93.000f};
constexpr Mm IN_INPUT = {12.000f, 113.500f};
constexpr Mm L_OUTPUT = {37.000f, 113.500f};
constexpr Mm R_OUTPUT = {50.500f, 113.500f};
} // namespace voices

namespace voices4
{
constexpr int HP = 12;
constexpr Mm LEVELS = {30.480f, 17.500f};
constexpr Mm PAN_1 = {9.030f, 36.000f};
constexpr Mm PAN_2 = {23.330f, 36.000f};
constexpr Mm PAN_3 = {37.630f, 36.000f};
constexpr Mm PAN_4 = {51.930f, 36.000f};
constexpr Mm PAN_CV_1 = {9.030f, 62.500f};
constexpr Mm PAN_CV_2 = {23.330f, 62.500f};
constexpr Mm PAN_CV_3 = {37.630f, 62.500f};
constexpr Mm PAN_CV_4 = {51.930f, 62.500f};
constexpr Mm IN_INPUT = {12.000f, 113.500f};
constexpr Mm L_OUTPUT = {37.000f, 113.500f};
constexpr Mm R_OUTPUT = {50.500f, 113.500f};
} // namespace voices4

namespace amp
{
constexpr int HP = 12;
constexpr Mm ATTACK = {10.230f, 18.500f};
constexpr Mm DECAY = {23.730f, 18.500f};
constexpr Mm SUSTAIN = {37.230f, 18.500f};
constexpr Mm RELEASE = {50.730f, 18.500f};
constexpr Mm CURVE = {16.980f, 32.000f};
constexpr Mm VELOCITY = {43.980f, 32.000f};
constexpr Mm ATTACK_ATT = {10.230f, 56.500f};
constexpr Mm ATTACK_INPUT = {10.230f, 71.000f};
constexpr Mm DECAY_ATT = {23.730f, 56.500f};
constexpr Mm DECAY_INPUT = {23.730f, 71.000f};
constexpr Mm SUSTAIN_ATT = {37.230f, 56.500f};
constexpr Mm SUSTAIN_INPUT = {37.230f, 71.000f};
constexpr Mm RELEASE_ATT = {50.730f, 56.500f};
constexpr Mm RELEASE_INPUT = {50.730f, 71.000f};
constexpr Mm IN_INPUT = {9.000f, 111.000f};
constexpr Mm GATE_INPUT = {20.500f, 111.000f};
constexpr Mm VEL_INPUT = {32.000f, 111.000f};
constexpr Mm OUT_OUTPUT = {43.500f, 111.000f};
constexpr Mm ENV_OUTPUT = {53.500f, 111.000f};
} // namespace amp

// Component geometry (mm)
constexpr float SLIDER_W = 10.5750f;
constexpr float HANDLE_W = 2.0250f;
} // namespace layout
